### ISSUE TITLE
Glitch on /is restart

### ISSUE THREAD

**Issue by Zivci** [rlf/uSkyBlock#235]
When a player issues /is restart, it either goes silent for a while or USB tells the player that he/her does not have the permission to do so. After approx. 15-20 seconds, the player respawns with a new island. This have been the case for the several latest builds, and it's not that bad. But, using the last build, it will also kick everyone off the server on a /is restart. It looks as if the server crashes and you get disconnected, but it haven't crashed in reality and you can reconnect at once, seeing that the /is restart have been finished. This happens to all players on the server, meaning that trolls that hit /is restart for fun kicks all players off, including operators. There is no error output in logs, it seems rather mystical, perhaps a glitch in the latest build? I don't know if anyone else have experienced this. I'm running latest USB build with latest Spigot-build under BC. Thanks!

**Comment by rlf** [comment]
First - read the posting guidelines.
We have no way of figuring out what "latest build" means.
It sounds like some of the stuff fixed in v2.2-HF4.

**Comment by Zivci** [comment]
Misconfig and Old version, I see. Alright then, let's do this.

Server: Spigot git-Spigot-b1e6da1-1092acb (MC: 1.8) (Build date: Jan 20th, 2015)
uSkyBlock: 2.2-HF5
Vault: 1.5.2-b33
WorldEdit: 6.0.0-SNAPSHOT
WorldGuard: 6.0.0-SNAPSHOT

Issue was originally reported on HF4 (as, the "latest version" published officially in repo as of date of ticket creation) but is persisting in HF5.

It goes like this:

[08:27:28] [Server thread/INFO]: Notorc issued server command: /is restart
[08:28:08] [Server thread/INFO]: Notorc lost connection: Disconnected
[08:28:08] [Server thread/INFO]: Zivci lost connection: Disconnected

A player hits /is restart, everything freezes for half a minute (like a read time-out) and everyone loses connection. Then, seconds after, it's all good again when you reconnect. Server never crashes or times out. It's something nasty that happens during /is restart.

I have no other plugins that should collide with uSB. Only latest published version (yes, a valid phrase) of Multiverse-Core and the Spigot-patch of Essentials for 1.8 [TeamCity].

Thank you.

**Comment by dutchy1001** [comment]
we have released a new version v2.2-HF7 (late last night) Hope this will fix your problem.

**Comment by rlf** [comment]
Doubt it will.
Seems that the performance improvements in HF4 isn't taking effect for you.
Might be a difference in WG version.

**Comment by Zivci** [comment]
I see.

"/worldedit version" returns:
Bukkit-Official (6.0.2-SNAPSHOT;3347-fe6717a0)

"/worldguard version" returns:
WorldGuard 6.0.0-SNAPSHOT

if that's of any help.

**Comment by rlf** [comment]
Can I get you to enable timings (Spigot only) `/timings on` and enable uSkyBlock logging (`/usb debug setlevel FINER`) and then retry the operations that cause the severe lag.

Afterwards, please post both the log-file from `/uSkyBlock/logs` and the timings report from `/timings paste`.

**Comment by Zivci** [comment]
/timings paste
http://timings.aikar.co/?url=10167960

/uSkyBlock/logs/uskyblock.2.log
http://paste.md-5.net/vetegisucu.coffee

Upon issuing /is restart, I get hanging in the air for 15-20 seconds, like the server has frozen. Then I get teleported to a X:0,Z:0 bedrock where I stand about a second or two before I'm finally teleported to my newly created island. I no longer get kicked off due to the "freezing" period, I've tested several times. Now I'm using the 2.2-HF7 though.

**Comment by rlf** [comment]
Thanks for the info.
I spot the error.
Will look into this.

**Comment by rlf** [comment]
But please upgrade to v2.2-HF9b

**Comment by rlf** [comment]
Most likely fixed in 9747e6038969a8557556354697f78eaf82e711d5 (will be in v2.2-HF10 release)

**Comment by dutchy1001** [comment]
I have not come across this issue, but as I only have a test server with 2 p;layers it is hard to say for me.

**Comment by dutchy1001** [comment]
No comment after 15 days of last post of the creator of this issue.

If problem still excists reopen or create a new issue
