### ISSUE TITLE
Error occurred during island-calculation of

### ISSUE THREAD

**Issue by Yselith** [rlf/uSkyBlock#254]
Sometime players falls and die, it happen if they want to sleep too.

It's with the 1.8.1 version on 1.7.10 serveur, i don't know if it's linked.
I already opened a ticket about the version problem: https://github.com/rlf/uSkyBlock/issues/253

Version: 2.2-HF4
Description: Ultimate SkyBlock v2.2-HF4-5a81f5-dev

Server: Cauldron-MCPC-Plus git-Cauldron-MCPC-Plus-1.7.10-1.1240.06.213 (MC: 1.7.10)

Name: Vault
Version: 1.4.1-b436 <== Maybe the cause ?

Name: WorldEdit
Version: 6.0;3342-78f975b9

Name: WorldGuard
Version: 6.0.0-beta-03.1514-

I get this log in the console when someone is falling:

java.lang.ArrayIndexOutOfBoundsException
[08:41:30 WARN]: Error occurred during island-calculation of 440,110

**Comment by Yselith** [comment]
I just got a bigger message after the update of vault to 1.5.2 and uSkyBlock to v2,2-HF9b

http://pastebin.com/mEfj7GTs

**Comment by Yselith** [comment]
No more access to the challenge:

http://pastebin.com/BeuaZFDs

**Comment by dutchy1001** [comment]
I think it will be the Cauldron-MCPC plus.
The uSkyblock is build on CraftBukkit and Spigot. 
After reading the main post again and I mixed "Carbon" (the protocol hack to use 1.8 items in a 1.7 server) up with "Cauldron" which is a total different version
Even that Cauldron is build on Forge/Spigot, there are significant changes to these versions.

**Comment by rlf** [comment]
The index-array out of bounds above is most likely caused by an invalid `levelConfig.yml` file.
It should be fixed in "later" releases, but you can manually make sure, that ALL keys are quoted.

**Comment by dutchy1001** [comment]
No input of the creator of this issue anymore.

If problem still excists reopen or create a new issue.
