### ISSUE TITLE
a bug at gui

### ISSUE THREAD

**Issue by a08381** [rlf/uSkyBlock#377]
Test on 'Travis-CI take 7'
give player these following permissions :
usb.island.*
usb.biome.*
usb.party.*
The bug is : 
when you issued /is and view the permission of your party , then you could pull them down if you don't have permission to change their permission .

![qq 20150518235750](https://cloud.githubusercontent.com/assets/2505002/7684608/060b52da-fdba-11e4-864b-524d1ea6c19a.png)
![qq 20150518235831](https://cloud.githubusercontent.com/assets/2505002/7684609/061beafa-fdba-11e4-9182-37d280ef8812.png)

**Comment by dutchy1001** [comment]
That you can take items out the GUI is known. We have been working on the issue but still haven't been able to fix it totally (there are some other issue's aswell with the language system).

**Comment by rlf** [comment]
Being able to take items out of the UI, is either bugs in the code, since i18n is still fairly new, or errors in translating (some terms must be identical for the menu system to work).

**Comment by rlf** [comment]
The Group Members menu was one of the java-code-bugs. It should be fixed in 81b42ee82b8a51107778c07df4aaaf26ed884475

**Comment by rlf** [comment]
Please re-test in v2.3-HF6, and report whether it persists.

**Comment by dutchy1001** [comment]
Tried to take item out the GUI without succes (which is good lol).

Fixed as far I can see for now in HF6b

**Comment by a08381** [comment]
The bug still exist. Test on HF6d

![qq 20150617232127](https://cloud.githubusercontent.com/assets/2505002/8211150/1cf96176-1548-11e5-8ab4-3668e43dd88b.png)
![qq 20150617232146](https://cloud.githubusercontent.com/assets/2505002/8211151/1cfc9990-1548-11e5-991f-6a5c4a79378e.png)

**Comment by dutchy1001** [comment]
I just notests that you still use 1.7.2.
What depended plugins are you using?

Is there a reason you havent updated the server to 1.8 yet??

**Comment by a08381** [comment]
nop , I use spigot 1.8.6 with protocolsupport

This plugin can be seen here

http://www.spigotmc.org/resources/protocolsupport.7201/

**Comment by dutchy1001** [comment]
I will try this plugin tonight, I have a feeling this can be the cause (using old versions) of taking items out the GUI.

**Comment by a08381** [comment]
Hello, I have just tried client 1.8.6 to test this and it still be able to take out.

![qq 20150618180344](https://cloud.githubusercontent.com/assets/2505002/8228980/a079a8c4-15e5-11e5-984d-3e505919dac5.png)
![qq 20150618180404](https://cloud.githubusercontent.com/assets/2505002/8228987/a9c695d6-15e5-11e5-998b-c5755ca9f810.png)

**Comment by dutchy1001** [comment]
I cant reproduce this (even with the protocol plugin).
As asked before, what depended plugins are you using?
This is crucial to as USB is very sensitive about some versions. Plz do "/usb version" ingame or "usb version" in console and post it here.

**Comment by a08381** [comment]
if you don't find any problem, that maybe it cause because of my translation file, let me see......

**Comment by dutchy1001** [comment]
can you answer the depended plugind question first plz.

**Comment by a08381** [comment]
OkayOkay.....here is the depended plugins

![20150619010441](https://cloud.githubusercontent.com/assets/2505002/8237111/8a1f209c-161f-11e5-88e0-627b675bced1.png)

**Comment by dutchy1001** [comment]
Both [WorldEdit](http://builds.enginehub.org/job/worldedit?branch=master) and [WorldGuard](http://builds.enginehub.org/job/worldguard?branch=master) can be updated (links are to dev build versions which I can recommend).

How have you enabled the translation? Is this build in translation or did you add your own translation?

**Comment by a08381** [comment]
uhh, I just rename the properties file in the folder i18n to enable translation. I use the translation file that once you put in that folder. And it seem like the title of biome gui haven't translate and this gui can take iten out in both pt_BR and zn_CN

**Comment by dutchy1001** [comment]
if you change back to "en" (default), can you still take items out the GUI??

**Comment by a08381** [comment]
nop, if I change back to en, I couldn't take them out

**Comment by dutchy1001** [comment]
as I cant reproduce it it's hard to fix it. I might need to visit your server and see. Pm me the server adress In bukkit or spigot or post it here

**Comment by rlf** [comment]
This is caused by two translations not being the same (in chinese).
Make sure the terms reg. menu-items / menu-titles are all translated the same way (to the same characters).

I.e. all texts referring to `Island Group Members` must contain the same string in the translation.
Otherwise, the plugin cannot detect that the menu is a "uSkyBlock menu".

**Comment by dutchy1001** [comment]
Bugs mentioned here were due to the language system, this system will be changed. This issue will be obsolete then.

Closed
