### ISSUE TITLE
No items in chest on island restart

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#460]
Version info:
Name: {0}
uSkyBlockVersion: 2.3-HF8d
Description: Ultimate SkyBlock v2.3-HF8d-c32f5f-dev
______________________________
Server: CraftBukkit git-Spigot-76236cb-9cd1111 (MC: 1.8.8)
______________________________
Name: Vault (ENABLED)
Version: 1.5.6-b49
______________________________
Name: WorldEdit (ENABLED)
Version: 6.1.1-SNAPSHOT;3394-9a65bdb7
______________________________
Name: WorldGuard (ENABLED)
Version: 6.1.1-SNAPSHOT.1629-0fcd42f
_____________________________

When restarting an island, the chest is empty.
Here's the log: http://pastebin.com/raw.php?i=1Fyq20cf
It seems it sees it as a bad schematic. Not sure why.

**Comment by BlackBeltPanda** [comment]
Also, I wasn't teleported back to the island after the restart; I had to teleport there manually with "/is h".

**Comment by dutchy1001** [comment]
the teleport is known, your empty chest is something i cant reproduce

**Comment by dutchy1001** [comment]
the teleport has been fixed, but still havent got the empty chest when creating an island

**Comment by BlackBeltPanda** [comment]
I'm still having the teleport issue with certain schematics, as well as empty starter chests.
I can't figure out why some of my schematics work and others don't. Are there any rules to creating an island schematic now? I've even placed the chest directly on top of the bedrock to ensure it's close enough to be found.

**Comment by BlackBeltPanda** [comment]
Here's one of the schematics that doesn't work. When using this one, I'm not teleported back after restarting and my starter chest is empty. https://www.dropbox.com/s/3tsdocic8x261d3/jonin.schematic?dl=0

**Comment by voigtman** [comment]
The running water beside your bedrock... I believe that's your problem with this schematic..

**Comment by dutchy1001** [comment]
I put your jonin.schem in the our test server and my chest got filled and it teleported me back to the island. I have to say that it took atleast 30 seconds before I was teleported, this can be due to the size of the island (or my crappy hardware). 
What I do think is weird is that the vines are not growing and water is not going down under the island but when placing my own water it does, have you done anything with MCEdit to the island?

**Comment by rlf** [comment]
Harry made a performance improvement, where we use world-edit in fast mode (meaning no physics is triggered).

It's a world-edit "feature".

**Comment by dutchy1001** [comment]
thx for clearing this up

**Comment by BlackBeltPanda** [comment]
Voigtman, I tried moving the bedrock away from any water first and it still wasn't working for me.

Think the issue could have something to do with aSyncWorldEdit?

**Comment by dutchy1001** [comment]
aSyncWorldEdit is indeed the cause of this, I tried this on my local test server and reproduced the error.
Not sure if we can fix this or that aSyncWorldEdit has to do it.

**Comment by BlackBeltPanda** [comment]
My guess is the chest may not be physically loaded in time due to AWE loading things in pieces, so USB doesn't see it when it scans. Probably not something AWE can fix; only fix I can think of for USB is a slight delay on scanning for the chest and teleporting the player.

**Comment by rlf** [comment]
We already have quite many delays... not sure we want more. We do not detect wheter AWE is in use, but if we find it to be a consistent delay, or possible to wait for AWE to finish, we could probably fix it on our side.

**Comment by voigtman** [comment]
I think AWE is a commonly used addition to large servers where WE in installed. It maybe a good thing to consider for an update. 

--
Sent from my iPhone 
--
Jason Houge
http://jasonhouge.com
http://instagram.com/jasonhouge


On Sep 10, 2015, at 1:01 PM, Razorax <notifications@github.com> wrote:

We already have quite many delays... not sure we want more. We do not detect wheter AWE is in use, but if we find it to be a consistent delay, or possible to wait for AWE to finish, we could probably fix it on our side.

**Comment by csorrows** [comment]
I agree. I ALWAYS recommend server owners to install AWE if they are using WE. Every uskyblock server I have worked on has it. I would add it as a soft depend and wait for it to finish.

**Comment by csorrows** [comment]
I can't see it effecting the small little default island at all but with those with larger custom islands, it really could.

**Comment by BlackBeltPanda** [comment]
Asked SB_prime about listening for a finished paste: https://www.spigotmc.org/threads/asyncworldedit-premium-paid.79081/page-13#post-1004242

**Comment by rlf** [comment]
Ready for test on HF9d

Config delay: 

    # Delay in server ticks (20 ticks per second or 50ms per tick)
    options.advanced.delayChestUpdate: 10

**Comment by rlf** [comment]
We changed the fix again panda.
In v2.4.1 - we try to listen to AWE (experimentally) to know when to look for the chest.

It might not be 100% stable, esp. for large servers with many simultaneous restarts/creates.

**Comment by BlackBeltPanda** [comment]
Just tried the version with AWE support.
With the schematic I posted earlier using AWE, players are never teleported to their island after restart/creation. The chest is still empty and when I attempt to delete the island, I get the error, "That player does not exist!" or "That player does not have an island!"

**Comment by rlf** [comment]
Does the server-log have any clues Panda?
It seems our AWE support still has some kinks to be ironed out.
Do you get progress-feedback in the chat?
Could you perhaps share the failing schematic?

**Comment by BlackBeltPanda** [comment]
Going through the log, here's the summary of events:
Player issued "/is restart" twice.
Island cleared in 14.406 seconds.
Player never teleported back to island.
Player issued "/is h".
Player receives "island still generating" message.
I can't use "/is w <player>" but can use "/usb goto <player>".
I delete the island with "/usb island delete <player>".
Island cleared in 16.291 seconds.
Player creates island from "/is" menu.
New protected region created for player's island by player.
Finished creating player island.
Player still can't use "/is h".
Using "/usb goto <player>" takes me to the void near the center of the world.
No errors or further information in the log.

This is the schematic I used: https://www.dropbox.com/s/3tsdocic8x261d3/jonin.schematic?dl=0

**Comment by rlf** [comment]
Thank you.
Managed to reproduce it, our "experimental AWE support" is simply not good enough.
We will try to find another way.

**Comment by BlackBeltPanda** [comment]
Working in the latest version.
Suggestion: Add TitleManager support in addition to ActionBar. =)

**Comment by rlf** [comment]
We will, once we figure out what to do with it :)

Currently, the ActionBar is enough for only showing progress-updates (i.e. stuff we don't want to spam the chat-window with).

In v2.5, we plan to introduce a whole new skyworld_nether concept, there we will have a need for Titles as well... I think. *teaser-done*

**Comment by BlackBeltPanda** [comment]
I was referring to the action bar messages, since I use TitleManager for my action bars. =P
But can't wait to see what you do with titles. =D

**Comment by rlf** [comment]
That is easily done - will do (add optional support for TitleManager instead).

**Comment by csorrows** [comment]
I've seen some discussion of the nether islands. I'm excited to see what your team comes up with!
